In [3]:
import numpy as np

### Генерация одномерного массива разными способами

In [22]:
%%time
n1=np.arange(12 , dtype=float)
n1

CPU times: total: 0 ns
Wall time: 313 µs


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [29]:
%%time
np.random.random(100)

CPU times: total: 0 ns
Wall time: 108 µs


array([0.13454714, 0.63415797, 0.10344707, 0.16449663, 0.49190659,
       0.76941966, 0.92109164, 0.8039639 , 0.12299696, 0.09019686,
       0.79373223, 0.46377034, 0.87171004, 0.78935186, 0.3049166 ,
       0.75686737, 0.2876595 , 0.99021946, 0.7236688 , 0.63260957,
       0.87148325, 0.41258715, 0.9137284 , 0.31024761, 0.96736526,
       0.72965717, 0.04349967, 0.81522176, 0.39457087, 0.01647694,
       0.48003413, 0.36902239, 0.54491503, 0.12684348, 0.96858406,
       0.27663947, 0.27963152, 0.68748832, 0.89055424, 0.93091356,
       0.60845814, 0.05390634, 0.20944879, 0.50367959, 0.9416183 ,
       0.45486377, 0.72218666, 0.40718844, 0.40890613, 0.6862235 ,
       0.04611656, 0.24172716, 0.7113936 , 0.46487176, 0.21576017,
       0.06571281, 0.36310643, 0.3535018 , 0.33185162, 0.3270064 ,
       0.95508798, 0.47921627, 0.86985144, 0.67917099, 0.4826694 ,
       0.77688584, 0.07502956, 0.76802845, 0.78750113, 0.73064728,
       0.05335312, 0.2797913 , 0.8503352 , 0.59093694, 0.48934

In [31]:
%%time
np.arange(0, 6, 0.6)

CPU times: total: 0 ns
Wall time: 0 ns


array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

### Генерация двумерного массива

In [30]:
%%time
np.random.random((3,3))

CPU times: total: 0 ns
Wall time: 0 ns


array([[0.4553934 , 0.72783682, 0.18885251],
       [0.1204414 , 0.17556987, 0.45300133],
       [0.82676591, 0.63510089, 0.28143591]])

In [21]:
%%time
np.arange(0, 1200000, 0.5, dtype=float).reshape(600000, 4)


CPU times: total: 0 ns
Wall time: 6.62 ms


array([[0.0000000e+00, 5.0000000e-01, 1.0000000e+00, 1.5000000e+00],
       [2.0000000e+00, 2.5000000e+00, 3.0000000e+00, 3.5000000e+00],
       [4.0000000e+00, 4.5000000e+00, 5.0000000e+00, 5.5000000e+00],
       ...,
       [1.1999940e+06, 1.1999945e+06, 1.1999950e+06, 1.1999955e+06],
       [1.1999960e+06, 1.1999965e+06, 1.1999970e+06, 1.1999975e+06],
       [1.1999980e+06, 1.1999985e+06, 1.1999990e+06, 1.1999995e+06]])

### Сравнение производительности

In [49]:
%%time
np.random.random(100)

CPU times: total: 0 ns
Wall time: 1 ms


array([0.0929659 , 0.06558713, 0.50444879, 0.50551552, 0.45905877,
       0.63698791, 0.43578996, 0.33850801, 0.82092247, 0.43132795,
       0.53238146, 0.25151972, 0.08004462, 0.99001129, 0.94314707,
       0.99683025, 0.1832249 , 0.10300617, 0.16387882, 0.43461053,
       0.87237624, 0.03674865, 0.34231054, 0.71016821, 0.6061694 ,
       0.84969589, 0.72741973, 0.65354067, 0.207501  , 0.26775462,
       0.46616005, 0.67781317, 0.59100053, 0.77086576, 0.7522802 ,
       0.81750509, 0.21074834, 0.69321235, 0.07646346, 0.34914438,
       0.99559056, 0.12116645, 0.45268195, 0.2652913 , 0.65426001,
       0.78939674, 0.30909555, 0.92052527, 0.25809763, 0.92902067,
       0.48157814, 0.41640248, 0.8409645 , 0.41301642, 0.04052256,
       0.51416086, 0.86293959, 0.94058168, 0.1711705 , 0.05557041,
       0.52634157, 0.66214507, 0.91721377, 0.42504282, 0.5691286 ,
       0.12139939, 0.71906428, 0.40133043, 0.55919301, 0.42367011,
       0.60900038, 0.39120623, 0.75754701, 0.96189084, 0.93410

In [54]:
import random

def sample_floats(low, high, k=1):
    """ Return a k-length list of unique random floats
        in the range of low <= x <= high
    """
    result = []
    seen = set()
    for i in range(k):
        x = random.uniform(low, high)
        while x in seen:
            x = random.uniform(low, high)
        seen.add(x)
        result.append(x)
    return result

In [55]:

%%time 
sample_floats(0,1,100)

CPU times: total: 0 ns
Wall time: 1.02 ms


[0.4831169139089472,
 0.6426716619452851,
 0.5580928359153244,
 0.020157766037107616,
 0.8003767994598787,
 0.22744397844054076,
 0.18511099324136515,
 0.2603901191009792,
 0.6915761182999797,
 0.7827755347696876,
 0.6214987289047581,
 0.36241198475995107,
 0.34493361066444916,
 0.7490160417258879,
 0.22005309034815568,
 0.7578582783720458,
 0.969446507078966,
 0.4817666313699317,
 0.3602816003849655,
 0.2940013444077729,
 0.1125267670380079,
 0.8930008649338588,
 0.03790166467589695,
 0.7516289041877792,
 0.3969827329350559,
 0.016421858748829843,
 0.6132017785935086,
 0.12828425875419913,
 0.43822967762026555,
 0.03770199208076508,
 0.9196047876955772,
 0.7783593849966611,
 0.29739944179874733,
 0.5525439705594525,
 0.6310259692458015,
 0.9863376542359753,
 0.05623554861909419,
 0.0974780096978739,
 0.12972096099556918,
 0.4821415564676008,
 0.30625043111791883,
 0.8548006678127461,
 0.6518572937988387,
 0.9323736151442196,
 0.6946935230918361,
 0.4517700056639721,
 0.220658167088367

In [41]:
%%time
np.random.random(1000)

CPU times: total: 0 ns
Wall time: 0 ns


array([5.87163108e-01, 5.79743875e-01, 9.85340733e-01, 1.83882004e-01,
       2.53430887e-01, 2.45434014e-01, 5.81294832e-01, 5.87114516e-01,
       4.92093420e-01, 7.17489110e-01, 4.20371858e-01, 4.64312921e-01,
       3.87445552e-02, 7.95077730e-01, 2.19849727e-01, 3.45773458e-01,
       5.83342403e-01, 8.73953840e-01, 4.32003152e-01, 3.43659290e-01,
       2.01162700e-01, 9.43033902e-01, 7.41758534e-01, 8.07114704e-01,
       7.10858180e-01, 4.26253520e-01, 3.73657245e-01, 1.76935413e-01,
       3.01548663e-01, 9.21629119e-01, 1.12334074e-01, 1.21529408e-01,
       2.80989243e-01, 9.26874466e-01, 5.05519298e-01, 8.08715499e-01,
       2.64196597e-01, 4.98705875e-01, 7.22074213e-01, 7.13986855e-01,
       8.32096255e-01, 4.35524522e-01, 5.41617997e-01, 7.73893652e-01,
       1.92376919e-01, 9.06922649e-01, 3.19055174e-01, 1.33682636e-01,
       3.16940934e-01, 8.51523572e-01, 6.34334537e-01, 1.13647852e-02,
       8.26809632e-01, 8.75162767e-01, 3.64091908e-01, 7.42859726e-01,
      

In [58]:
%%time 
sample_floats(0,1,1000)

CPU times: total: 0 ns
Wall time: 998 µs


[0.4877832217743404,
 0.684703405799811,
 0.3124363030732755,
 0.19665889134785042,
 0.08095732732563565,
 0.4652084918459771,
 0.7557953437635331,
 0.39589646616253293,
 0.23301054963562484,
 0.12110057663004126,
 0.685945077329745,
 0.4203115019194831,
 0.271770214487676,
 0.9690440778704045,
 0.05233874852637588,
 0.36243757058722126,
 0.9174884478176468,
 0.22969355394772373,
 0.36520923717346054,
 0.7708079997648564,
 0.9201626371855672,
 0.6886212996321335,
 0.8909392352662867,
 0.4610205960658662,
 0.8939603014866513,
 0.42992290811344136,
 0.5121071394076933,
 0.5777807025221691,
 0.17905560945285592,
 0.7415417394636796,
 0.6177564009133292,
 0.9014192260327029,
 0.13989569427915638,
 0.039396843364475354,
 0.733494611380325,
 0.4851403677722457,
 0.5785699857345236,
 0.5409872938917418,
 0.050730972943106134,
 0.29252781215416446,
 0.3683543367476637,
 0.8966722332942741,
 0.7510283969731361,
 0.4781868139270785,
 0.004407011616611722,
 0.4533559075314303,
 0.3203452950114545

In [44]:
%%time
np.random.random(90000)

CPU times: total: 0 ns
Wall time: 1.71 ms


array([0.82598647, 0.36699557, 0.00597796, ..., 0.50943007, 0.29639202,
       0.99019174])

In [59]:
%%time 
sample_floats(0,1,90000)

CPU times: total: 78.1 ms
Wall time: 97.4 ms


[0.26338011016607743,
 0.18548303763516238,
 0.40441422695057794,
 0.9720431920022162,
 0.23973276164278667,
 0.5937430992378291,
 0.07693662508768562,
 0.6017440763111562,
 0.4791318746413469,
 0.620017186166943,
 0.6713659060954722,
 0.9628688563844148,
 0.9396000682526199,
 0.8054004989149965,
 0.09178408600313659,
 0.8287073359032314,
 0.15003600330193512,
 0.5971151561608412,
 0.4768770858745166,
 0.9445109441576948,
 0.13881069151926484,
 0.8802232964508018,
 0.2009280992180209,
 0.33002653039197816,
 0.038166544573456695,
 0.4696938283239971,
 0.9474001858049693,
 0.5912790501073261,
 0.16287746412794035,
 0.553535093255969,
 0.9562069594756951,
 0.3168899381349727,
 0.28062743856681305,
 0.5648347026346516,
 0.23618685054876043,
 0.1287502761984668,
 0.8908565871170802,
 0.7316479781058979,
 0.6645268726389977,
 0.3139151683273341,
 0.8753016570737551,
 0.46255231188637647,
 0.03234068550118119,
 0.26836901859470574,
 0.07246837882031876,
 0.7574869324990484,
 0.360667979992333

In [63]:
%%time
np.random.random((100,100))

CPU times: total: 0 ns
Wall time: 0 ns


array([[0.21764146, 0.89219332, 0.61110164, ..., 0.35248453, 0.99455234,
        0.44189987],
       [0.73150473, 0.13901027, 0.3506199 , ..., 0.60970405, 0.15378582,
        0.84097026],
       [0.91022222, 0.74193438, 0.71694924, ..., 0.49236885, 0.38048676,
        0.4407648 ],
       ...,
       [0.5462965 , 0.18503019, 0.39314847, ..., 0.72097609, 0.87133463,
        0.89748275],
       [0.04147804, 0.44088517, 0.32208002, ..., 0.8122075 , 0.78442212,
        0.0418724 ],
       [0.48285394, 0.90060887, 0.13402132, ..., 0.9785624 , 0.44212152,
        0.95930378]])

In [75]:
%%time
random_matrix100 = [[random.random() for e in range(100)] for e in range(100)]


CPU times: total: 0 ns
Wall time: 0 ns


In [66]:
%%time
np.random.random((1000,1000))

CPU times: total: 15.6 ms
Wall time: 12 ms


array([[0.29165339, 0.34318796, 0.611815  , ..., 0.250547  , 0.56743883,
        0.78845542],
       [0.43525871, 0.63918157, 0.31526237, ..., 0.38255436, 0.46025119,
        0.45402819],
       [0.25428377, 0.96591519, 0.39746507, ..., 0.5257427 , 0.53965512,
        0.60208177],
       ...,
       [0.46425105, 0.67642191, 0.13871249, ..., 0.48128894, 0.04735539,
        0.76135795],
       [0.21053383, 0.90454474, 0.96694204, ..., 0.41762482, 0.25046237,
        0.90994221],
       [0.73769716, 0.9669403 , 0.25396312, ..., 0.28944158, 0.79975744,
        0.53581986]])

In [74]:
%%time
random_matrix1000 = [[random.random() for e in range(1000)] for e in range(1000)]


CPU times: total: 188 ms
Wall time: 189 ms


In [73]:
%%time
np.random.random((10000,10000))

CPU times: total: 1.08 s
Wall time: 1.09 s


array([[0.48572856, 0.64485207, 0.77663003, ..., 0.44364593, 0.25160106,
        0.44607968],
       [0.37022357, 0.22231328, 0.01771528, ..., 0.30675217, 0.65862439,
        0.96597281],
       [0.04254286, 0.91336127, 0.62531197, ..., 0.09215827, 0.56865689,
        0.93730057],
       ...,
       [0.35987859, 0.79063459, 0.26051261, ..., 0.63938966, 0.25839177,
        0.88564715],
       [0.93397334, 0.34511789, 0.31304109, ..., 0.01560658, 0.30316994,
        0.46086342],
       [0.9840969 , 0.77278243, 0.72698706, ..., 0.68441621, 0.23976372,
        0.17700113]])

In [72]:
%%time
random_matrix10000 = [[random.random() for e in range(10000)] for e in range(10000)]


CPU times: total: 14.2 s
Wall time: 14.2 s


#### Вывод: Numpy позволяет генерировать массивы на порядок быстрее

## Арифметические операции над матрицами

In [5]:
x1=np.random.random((5,5))
x1

array([[0.92293088, 0.59890284, 0.23188416, 0.45313459, 0.7967056 ],
       [0.98327275, 0.63009272, 0.05507494, 0.52057241, 0.25353186],
       [0.15583412, 0.21645082, 0.68656078, 0.38351553, 0.64682183],
       [0.7180143 , 0.45462941, 0.79912626, 0.00905489, 0.31749264],
       [0.34531377, 0.35072505, 0.00617953, 0.14939797, 0.96255969]])

In [23]:
x2=np.ones((5,5))
x2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
x3=x2+x1
x3

array([[1.92293088, 1.59890284, 1.23188416, 1.45313459, 1.7967056 ],
       [1.98327275, 1.63009272, 1.05507494, 1.52057241, 1.25353186],
       [1.15583412, 1.21645082, 1.68656078, 1.38351553, 1.64682183],
       [1.7180143 , 1.45462941, 1.79912626, 1.00905489, 1.31749264],
       [1.34531377, 1.35072505, 1.00617953, 1.14939797, 1.96255969]])

In [24]:
x4=np.ones((5,1))
x4

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [26]:
x3+x4

array([[2.92293088, 2.59890284, 2.23188416, 2.45313459, 2.7967056 ],
       [2.98327275, 2.63009272, 2.05507494, 2.52057241, 2.25353186],
       [2.15583412, 2.21645082, 2.68656078, 2.38351553, 2.64682183],
       [2.7180143 , 2.45462941, 2.79912626, 2.00905489, 2.31749264],
       [2.34531377, 2.35072505, 2.00617953, 2.14939797, 2.96255969]])

In [19]:
x1-x2

array([[-0.07706912, -0.40109716, -0.76811584, -0.54686541, -0.2032944 ],
       [-0.01672725, -0.36990728, -0.94492506, -0.47942759, -0.74646814],
       [-0.84416588, -0.78354918, -0.31343922, -0.61648447, -0.35317817],
       [-0.2819857 , -0.54537059, -0.20087374, -0.99094511, -0.68250736],
       [-0.65468623, -0.64927495, -0.99382047, -0.85060203, -0.03744031]])

In [27]:
x1-x4

array([[-0.07706912, -0.40109716, -0.76811584, -0.54686541, -0.2032944 ],
       [-0.01672725, -0.36990728, -0.94492506, -0.47942759, -0.74646814],
       [-0.84416588, -0.78354918, -0.31343922, -0.61648447, -0.35317817],
       [-0.2819857 , -0.54537059, -0.20087374, -0.99094511, -0.68250736],
       [-0.65468623, -0.64927495, -0.99382047, -0.85060203, -0.03744031]])

In [20]:
x1*x3

array([[1.7747323 , 0.95758746, 0.28565442, 0.65846554, 1.43144542],
       [1.95009805, 1.02710955, 0.05810819, 0.79156805, 0.31781026],
       [0.18011839, 0.26330178, 1.15792648, 0.53059969, 1.0652003 ],
       [1.23355883, 0.66131732, 1.43772903, 0.00913689, 0.41829421],
       [0.46455536, 0.47373311, 0.00621771, 0.17171772, 1.88908084]])

In [28]:
x1/x3

array([[0.47996051, 0.37457113, 0.18823536, 0.3118325 , 0.44342579],
       [0.49578292, 0.38653796, 0.05220003, 0.34235292, 0.20225402],
       [0.13482395, 0.17793635, 0.4070774 , 0.27720363, 0.39276977],
       [0.41793267, 0.31253968, 0.44417464, 0.00897364, 0.24098248],
       [0.25667898, 0.25965688, 0.00614158, 0.12997932, 0.49046136]])

### Список арефметических операций numpy


add(x1, x2, /[, out, where, casting, order, ...])
Add arguments element-wise.

reciprocal(x, /[, out, where, casting, ...])
Return the reciprocal of the argument, element-wise.

positive(x, /[, out, where, casting, order, ...])
Numerical positive, element-wise.

negative(x, /[, out, where, casting, order, ...])
Numerical negative, element-wise.

multiply(x1, x2, /[, out, where, casting, ...])
Multiply arguments element-wise.

divide(x1, x2, /[, out, where, casting, ...])
Divide arguments element-wise.

power(x1, x2, /[, out, where, casting, ...])
First array elements raised to powers from second array, element-wise.

subtract(x1, x2, /[, out, where, casting, ...])
Subtract arguments, element-wise.

true_divide(x1, x2, /[, out, where, ...])
Divide arguments element-wise.

floor_divide(x1, x2, /[, out, where, ...])
Return the largest integer smaller or equal to the division of the inputs.

float_power(x1, x2, /[, out, where, ...])
First array elements raised to powers from second array, element-wise.

fmod(x1, x2, /[, out, where, casting, ...])
Returns the element-wise remainder of division.

mod(x1, x2, /[, out, where, casting, order, ...])
Returns the element-wise remainder of division.

modf(x[, out1, out2], / [[, out, where, ...])
Return the fractional and integral parts of an array, element-wise.

remainder(x1, x2, /[, out, where, casting, ...])
Returns the element-wise remainder of division.

divmod(x1, x2[, out1, out2], / [[, out, ...])
Return element-wise quotient and remainder simultaneously.

In [31]:
np.add(x1,x2)

array([[1.92293088, 1.59890284, 1.23188416, 1.45313459, 1.7967056 ],
       [1.98327275, 1.63009272, 1.05507494, 1.52057241, 1.25353186],
       [1.15583412, 1.21645082, 1.68656078, 1.38351553, 1.64682183],
       [1.7180143 , 1.45462941, 1.79912626, 1.00905489, 1.31749264],
       [1.34531377, 1.35072505, 1.00617953, 1.14939797, 1.96255969]])

In [32]:
np.reciprocal(x1)

array([[  1.08350475,   1.66971991,   4.31249809,   2.20684987,
          1.25516878],
       [  1.01701181,   1.58706801,  18.15707887,   1.92096234,
          3.94427745],
       [  6.4170799 ,   4.61998701,   1.45653529,   2.60745636,
          1.54602081],
       [  1.39272992,   2.19959372,   1.25136672, 110.4375171 ,
          3.14967934],
       [  2.89591698,   2.85123631, 161.82465664,   6.69353133,
          1.03889661]])

In [33]:
np.positive(x1)

array([[0.92293088, 0.59890284, 0.23188416, 0.45313459, 0.7967056 ],
       [0.98327275, 0.63009272, 0.05507494, 0.52057241, 0.25353186],
       [0.15583412, 0.21645082, 0.68656078, 0.38351553, 0.64682183],
       [0.7180143 , 0.45462941, 0.79912626, 0.00905489, 0.31749264],
       [0.34531377, 0.35072505, 0.00617953, 0.14939797, 0.96255969]])

In [34]:
np.negative(x1)

array([[-0.92293088, -0.59890284, -0.23188416, -0.45313459, -0.7967056 ],
       [-0.98327275, -0.63009272, -0.05507494, -0.52057241, -0.25353186],
       [-0.15583412, -0.21645082, -0.68656078, -0.38351553, -0.64682183],
       [-0.7180143 , -0.45462941, -0.79912626, -0.00905489, -0.31749264],
       [-0.34531377, -0.35072505, -0.00617953, -0.14939797, -0.96255969]])

In [37]:
np.multiply(x1,x3)

array([[1.7747323 , 0.95758746, 0.28565442, 0.65846554, 1.43144542],
       [1.95009805, 1.02710955, 0.05810819, 0.79156805, 0.31781026],
       [0.18011839, 0.26330178, 1.15792648, 0.53059969, 1.0652003 ],
       [1.23355883, 0.66131732, 1.43772903, 0.00913689, 0.41829421],
       [0.46455536, 0.47373311, 0.00621771, 0.17171772, 1.88908084]])

In [54]:
np.divide(x3,x1)

array([[  2.08350475,   2.66971991,   5.31249809,   3.20684987,
          2.25516878],
       [  2.01701181,   2.58706801,  19.15707887,   2.92096234,
          4.94427745],
       [  7.4170799 ,   5.61998701,   2.45653529,   3.60745636,
          2.54602081],
       [  2.39272992,   3.19959372,   2.25136672, 111.4375171 ,
          4.14967934],
       [  3.89591698,   3.85123631, 162.82465664,   7.69353133,
          2.03889661]])

In [42]:
np.power(x1,x3)

array([[0.85708272, 0.44056955, 0.16522947, 0.31655696, 0.66475457],
       [0.96709814, 0.4709889 , 0.04694746, 0.37058604, 0.17903412],
       [0.11664116, 0.15541653, 0.53033366, 0.26555669, 0.4879733 ],
       [0.56602368, 0.31770099, 0.66802514, 0.00867727, 0.22056559],
       [0.23919538, 0.24287076, 0.00598831, 0.11245881, 0.92784581]])

In [44]:
np.subtract(x1,x2)

array([[-0.07706912, -0.40109716, -0.76811584, -0.54686541, -0.2032944 ],
       [-0.01672725, -0.36990728, -0.94492506, -0.47942759, -0.74646814],
       [-0.84416588, -0.78354918, -0.31343922, -0.61648447, -0.35317817],
       [-0.2819857 , -0.54537059, -0.20087374, -0.99094511, -0.68250736],
       [-0.65468623, -0.64927495, -0.99382047, -0.85060203, -0.03744031]])

In [53]:
np.true_divide(x3,x1)

array([[  2.08350475,   2.66971991,   5.31249809,   3.20684987,
          2.25516878],
       [  2.01701181,   2.58706801,  19.15707887,   2.92096234,
          4.94427745],
       [  7.4170799 ,   5.61998701,   2.45653529,   3.60745636,
          2.54602081],
       [  2.39272992,   3.19959372,   2.25136672, 111.4375171 ,
          4.14967934],
       [  3.89591698,   3.85123631, 162.82465664,   7.69353133,
          2.03889661]])

In [52]:
np.floor_divide(x3,x1)

array([[  2.,   2.,   5.,   3.,   2.],
       [  2.,   2.,  19.,   2.,   4.],
       [  7.,   5.,   2.,   3.,   2.],
       [  2.,   3.,   2., 111.,   4.],
       [  3.,   3., 162.,   7.,   2.]])

In [55]:
np.float_power(x3,x1)

array([[1.82843213, 1.32455385, 1.04954658, 1.18453089, 1.59493574],
       [1.96068603, 1.36054663, 1.00295703, 1.24379234, 1.05896217],
       [1.02282484, 1.04332301, 1.43169552, 1.13258177, 1.38080312],
       [1.47486607, 1.18574694, 1.59891897, 1.00008163, 1.09148852],
       [1.10785917, 1.11120222, 1.00003807, 1.02101979, 1.91363671]])

In [56]:
np.fmod(x3,x1)

array([[0.07706912, 0.40109716, 0.07246336, 0.09373083, 0.2032944 ],
       [0.01672725, 0.36990728, 0.00865111, 0.47942759, 0.23940442],
       [0.06499528, 0.1341967 , 0.31343922, 0.23296895, 0.35317817],
       [0.2819857 , 0.09074117, 0.20087374, 0.00396167, 0.04752209],
       [0.30937247, 0.2985499 , 0.00509599, 0.10361217, 0.03744031]])

In [57]:
np.mod(x3,x1)

array([[0.07706912, 0.40109716, 0.07246336, 0.09373083, 0.2032944 ],
       [0.01672725, 0.36990728, 0.00865111, 0.47942759, 0.23940442],
       [0.06499528, 0.1341967 , 0.31343922, 0.23296895, 0.35317817],
       [0.2819857 , 0.09074117, 0.20087374, 0.00396167, 0.04752209],
       [0.30937247, 0.2985499 , 0.00509599, 0.10361217, 0.03744031]])

In [68]:
np.modf(x3)

(array([[0.92293088, 0.59890284, 0.23188416, 0.45313459, 0.7967056 ],
        [0.98327275, 0.63009272, 0.05507494, 0.52057241, 0.25353186],
        [0.15583412, 0.21645082, 0.68656078, 0.38351553, 0.64682183],
        [0.7180143 , 0.45462941, 0.79912626, 0.00905489, 0.31749264],
        [0.34531377, 0.35072505, 0.00617953, 0.14939797, 0.96255969]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [69]:
np.remainder(x3,x1)

array([[0.07706912, 0.40109716, 0.07246336, 0.09373083, 0.2032944 ],
       [0.01672725, 0.36990728, 0.00865111, 0.47942759, 0.23940442],
       [0.06499528, 0.1341967 , 0.31343922, 0.23296895, 0.35317817],
       [0.2819857 , 0.09074117, 0.20087374, 0.00396167, 0.04752209],
       [0.30937247, 0.2985499 , 0.00509599, 0.10361217, 0.03744031]])

In [71]:
np.divmod(x3,x1)

(array([[  2.,   2.,   5.,   3.,   2.],
        [  2.,   2.,  19.,   2.,   4.],
        [  7.,   5.,   2.,   3.,   2.],
        [  2.,   3.,   2., 111.,   4.],
        [  3.,   3., 162.,   7.,   2.]]),
 array([[0.07706912, 0.40109716, 0.07246336, 0.09373083, 0.2032944 ],
        [0.01672725, 0.36990728, 0.00865111, 0.47942759, 0.23940442],
        [0.06499528, 0.1341967 , 0.31343922, 0.23296895, 0.35317817],
        [0.2819857 , 0.09074117, 0.20087374, 0.00396167, 0.04752209],
        [0.30937247, 0.2985499 , 0.00509599, 0.10361217, 0.03744031]]))

## Игра "Жизнь" 
#### Реализовано для квадратной матрицы любого размера, которая вводится в поле ниже. 

In [287]:
x= np.array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [288]:
x

array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Функция, реализующая игру. При необходимости можно отобразить скрытые Print для более подробного анализа работы игры

In [289]:
def Zhizn (x):
    global a,b
    a=0
    b=0
    razmer=x.shape[0]-1
    
    itemindex2 = np.where(x == 0)
    #print(itemindex2)
    i=0
    for element in itemindex2[0]:
        raw=element
        #print(element)
        cc=itemindex2[1]
        column=cc[i]
        #print(column)
        i=i+1
        if razmer>column:
            z=x[raw,column+1]
            if (z==1):
                a=a+1       
        if column>0:
            z=x[raw,column-1]
            if (z==1):
                a=a+1
        if (razmer>column) and (razmer>raw):
            z=x[raw+1,column+1]
            if (z==1):
                a=a+1
        if (razmer>raw) and (column>0):
            z=x[raw+1,column-1]
            if (z==1):
                a=a+1
        if (column>0) and (raw>0):
            z=x[raw-1,column-1]
            if (z==1):
                a=a+1
        if (raw>0) and (razmer>column):
            z=x[raw-1,column+1]
            if (z==1):
                a=a+1
        if (raw>0):
            z=x[raw-1,column]
            if (z==1):
                a=a+1
        if (raw<razmer):
            z=x[raw+1,column]
            if (z==1):
                a=a+1
            
        #print(a)
        if (a > 2):
            x[raw,column]=1
        a=0
        
    itemindex = np.where(x == 1)
    #print(itemindex)
    i=0
    for element in itemindex[0]:
        raw=element
        #print(element)
        cc=itemindex[1]
        column=cc[i]
        #print(column)
        i=i+1
        if razmer>column:
            z=x[raw,column+1]
            if (z==1):
                b=b+1       
        if column>0:
            z=x[raw,column-1]
            if (z==1):
                b=b+1
        if (razmer>column) and (razmer>raw):
            z=x[raw+1,column+1]
            if (z==1):
                b=b+1
        if (razmer>raw) and (column>0):
            z=x[raw+1,column-1]
            if (z==1):
                b=b+1
        if (column>0) and (raw>0):
            z=x[raw-1,column-1]
            if (z==1):
                b=b+1
        if (raw>0) and (razmer>column):
            z=x[raw-1,column+1]
            if (z==1):
                b=b+1
        if (raw>0):
            z=x[raw-1,column]
            if (z==1):
                b=b+1
        if (raw<razmer):
            z=x[raw+1,column]
            if (z==1):
                b=b+1
            
        #print(a)
        if (b > 3) or (b<2) :
            x[raw,column]=0
        b=0
   
    return(x)

        
            

In [297]:
Zhizn(x)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.]])